#!/bin/sh

# share_dir=
: ${share_dir:="$(dirname "$0")"}

config="$1"
image="$2"

. "$(realpath "$config")"
. "${share_dir}/base.subr"
. "${share_dir}/img.subr"
. "${share_dir}/pkg.subr"

img_build "$image"
