#!/bin/sh

set -e

# share_dir=
: ${share_dir:="$(dirname "$0")"}

. "${share_dir}/sh/base.subr"
. "${share_dir}/sh/dev.subr"
. "${share_dir}/sh/img.subr"
. "${share_dir}/sh/pkg.subr"
. "${share_dir}/sh/step.subr"
. "${share_dir}/sh/run.subr"

run_getopt "$@"
step_config "$run_config" "$run_image" "$run_root"
step_run_steps $run_steps
